# Generated by Django 5.0.7 on 2024-07-29 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('price', models.CharField(max_length=100)),
                ('price_currency', models.CharField(max_length=10)),
                ('mileage', models.CharField(max_length=100)),
                ('fuel_type', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=4)),
                ('image_url', models.URLField()),
            ],
        ),
    ]
