# Generated by Django 5.0.7 on 2024-07-29 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_listing', '0002_car_gearbox_car_horsepower_car_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='engine_capacity',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
